In [1]:
import pickle

In [2]:
with open('model_pickle', 'rb') as file:
    Lin1 = pickle.load(file)

In [3]:
Lin1.predict([[3.5]])

array([58867.06832376])

In [4]:
Lin1.coef_

array([9449.96232146])

In [5]:
Lin1.intercept_

np.float64(25792.20019866871)

In [6]:
import joblib

In [7]:
Lin2 = joblib.load('model_joblib')

In [8]:
Lin2.coef_

array([9449.96232146])